services:
  crawl4ai:
    image: unclecode/crawl4ai:${VERSION:-basic}-amd64
    ports:
      - "11235:11235"
      - "8025:8000"
      - "9222:9222"
      - "8065:8080"
    environment:
      - CRAWL4AI_API_TOKEN=${CRAWL4AI_API_TOKEN:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY:-}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
      - MiniMax_TEXT_01_API_KEY=${MiniMax-Text-01_API_KEY:-}  
    volumes:
      - /dev/shm:/dev/shm
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    restart: unless-stopped
    labels:
      # Maintain existing Coolify labels
      - coolify.managed=true
      - coolify.version=4.0.0-beta.389
      - coolify.applicationId=8
      - coolify.type=application
      # Traefik specific configuration
      - traefik.enable=true
      - traefik.http.middlewares.gzip.compress=true
      - "traefik.http.routers.crawl4ai.rule=Host(`ysksokgkoocgs888wkg8o8wg.147.93.56.140.sslip.io`)"
      - "traefik.http.services.crawl4ai.loadbalancer.server.port=11235"
      - "traefik.http.services.crawl4ai.loadbalancer.healthcheck.path=/health"
      - "traefik.http.services.crawl4ai.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.crawl4ai.loadbalancer.healthcheck.timeout=5s"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11235/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - poc4okkwg4cko0g48w48sk08

networks:
  poc4okkwg4cko0g48w48sk08:
    external: true

